---
- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"
  tasks:
    - name: Check Caddy binary exists
      ansible.builtin.stat:
        path: "{{ caddy_bin_path }}"
      register: caddy_binary

    - name: Assert Caddy binary is present and executable
      ansible.builtin.assert:
        that:
          - caddy_binary.stat.exists
          - caddy_binary.stat.executable
        fail_msg: "Caddy binary is missing or not executable"

    - name: Check Cloudflare DNS module is available
      ansible.builtin.command: "{{ caddy_bin_path }} list-modules"
      register: caddy_modules
      changed_when: false

    - name: Assert Cloudflare DNS module is present
      ansible.builtin.assert:
        that:
          - "'dns.providers.cloudflare' in caddy_modules.stdout"
        fail_msg: "Cloudflare DNS module not found in Caddy build"
