---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Stop and mask apt daily services and timers (Ubuntu systemd containers)
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
        masked: true
        daemon_reload: true
      loop:
        - apt-daily.service
        - apt-daily.timer
        - apt-daily-upgrade.service
        - apt-daily-upgrade.timer
      when: ansible_facts.os_family == "Debian"
      ignore_errors: true

    - name: Remove apt/dpkg lock files (best effort)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
      when: ansible_facts.os_family == "Debian"
      ignore_errors: true
