---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: caddy-debian-12
    image: geerlingguy/docker-debian12-ansible:latest
    command: /lib/systemd/systemd
    user: root
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp:rw,mode=1777
  - name: caddy-debian-11
    image: geerlingguy/docker-debian11-ansible:latest
    command: /lib/systemd/systemd
    user: root
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp:rw,mode=1777

provisioner:
  name: ansible
  inventory:
    host_vars:
      caddy-debian-12:
        ansible_connection: community.docker.docker
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_remote_tmp: /tmp/.ansible/tmp
        caddy_install_method: apt
      caddy-debian-11:
        ansible_connection: community.docker.docker
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_remote_tmp: /tmp/.ansible/tmp
        caddy_install_method: apt

verifier:
  name: ansible
